# And this is how our first shared Python project begins :)

print("_______________________________")
print("                               ")
print("*** Welcome to Best Burgers ***")
print("_______________________________")
print("                                                                     ")
print(">>> I am here to guide you towards the Best Burgers you've ever had! <<<")
print("                                                                     ")
print("- What is your name?")
print("                    ")
name = input("")
print("                    ")
print("- Hello,",(name),"!")
